In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.26.4'

In [ ]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    versio

In [ ]:
a= [12.23, 13.32, 100, 36.32]
np.array(a)

array([ 12.23,  13.32, 100.  ,  36.32])

In [ ]:
a = np.arange(2,11).reshape(3,3)

In [ ]:
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
a=np.zeros(10)

In [ ]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
a[6]=11

In [ ]:
a

array([ 0.,  0.,  0.,  0.,  0., 11., 11.,  0.,  0.,  0.])

In [ ]:
s=np.arange(12,38)

In [ ]:
s[::-1]

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

In [ ]:
a = [1, 2, 3, 4]
x= np.asfarray(a)
x

array([1., 2., 3., 4.])

In [ ]:
s= np.ones((4,5))
s

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
s[1:3,1:4] = 0

In [ ]:
s

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
d = np.zeros((3,3))


In [ ]:
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)


In [ ]:
d = np.zeros((8,8),dtype=int)

In [ ]:
d

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
d[1::2,::2]=1
d[::2,1::2]=1
d


array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
d

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
import numpy as np
s=[1,2,3,4,5,6,7,8]
np.asarray(s)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = [10,20,30]
x = np.append(x,([40,50,60,70,80,90]))
x

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x= np.empty((3,4))

In [ ]:
x

array([[4.91325446e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [ ]:
y = np.full((4,3),5)

In [ ]:
y

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
for i in range(1500,2701):
  if (i%7==0) and (i%5==0):
    print(list(i))
    i += 1

TypeError: 'int' object is not iterable

In [ ]:
1505,1540,1575,1610,1645,1680,1715,1750,1785,1820,1855,1890,1925,1960,1995,2030,2065,2100,2135,2170,2205,2240,
2275,2310,2345,2380,2415,2450,2485,2520,2555,2590,2625,2660,2695

In [ ]:
import numpy as np

In [ ]:
x = np.array([1, 2, 3], dtype=np.float64)
np.size(x)


3

In [ ]:
x.nbytes

24

In [ ]:
x.itemsize

8

In [ ]:
a= [ 0,10,20,40,60]
b= [10, 30, 40]
arr = np.intersect1d(a,b)
arr


array([10, 40])

In [ ]:
a = [1, 2, 3, 4]
x = np.tile(a,3)
x

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])